import pwd
import sys

raise Exception("hello")